"""Constants for the firstbatch package."""

BASE_URL = "https://aws-eu-central-1.hollowdb.xyz/"

DEFAULT_QUANTIZER_TRAIN_SIZE = 100
DEFAULT_QUANTIZER_TYPE = "scalar"
DEFAULT_EMBEDDING_SIZE = 1536
DEFAULT_CONFIDENCE_INTERVAL_RATIO = 0.15
DEFAULT_COLLECTION = "my_collection"
DEFAULT_BATCH_SIZE = 10
DEFAULT_KEY = "text"
DEFAULT_TOPK_QUANT = 5
MINIMUM_TOPK = 5
DEFAULT_HISTORY = False
DEFAULT_VERBOSE = False

